package com.rest.services.god.persistence.hbm;


/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private String descripcion;
     private int precio;
 
    public Producto() {
    }

	
    public Producto(long idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(long idProducto, String descripcion, 
    		int precio) {
       this.idProducto = idProducto;
       this.descripcion = descripcion;
       this.precio = precio;
    }

    public long getIdProducto() {
        return idProducto;
    }

    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getPrecio() {
        return precio;
    }

    public void setPrecio(int precio) {
        this.precio = precio;
    }

    
}


