@REM FILE BATCH FOR COMPILING PROJECT IMSS BY ULY_MAK
@ECHO off

@REM VARIABLES DEL BATCH
COLOR 70
	
@REM LIMPIA LA CONSOLA ANTES DE CONTINUAR
	REM CLS
	
@REM TRUE==COMPILAR, FALSE==IGNORAR
	SET STATUS_ADAPTER=TRUE
	SET STATUS_DROOLS=TRUE
	SET STATUS_PERSISTENCE=TRUE
	SET STATUS_WEB=TRUE

@REM PATHS DE LAS RUTAS DE LOS PROYECTOS
	SET RAIZ=C:\temporal\god\god-doc\
	SET ADAPTER=C:\temporal\god\god-adapter\
	SET DROOLS=C:\temporal\god\god-drools\
	SET PERSISTENCE=C:\temporal\god\god-persistence\
	SET WEB=C:\temporal\god\god-web
	SET COMPILAR_MODO_NORMAL=mvn clean compile install -Dmaven.test.skip=true
	
	IF %STATUS_ADAPTER% EQU TRUE (
		CD %ADAPTER%
		CALL %COMPILAR_MODO_NORMAL%)
	IF %STATUS_DROOLS% EQU TRUE (
		CD %DROOLS%
		CALL %COMPILAR_MODO_NORMAL%)
	IF %STATUS_PERSISTENCE% EQU TRUE (
		CD %PERSISTENCE%
		CALL %COMPILAR_MODO_NORMAL%)
	IF %STATUS_WEB% EQU TRUE (
		CD %WEB%
		CALL %COMPILAR_MODO_NORMAL%)
	CD %RAIZ%